services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner-web
    command: node server.js
    ports:
      - "3000:3000"
    networks:
      - enginy-network-prod
    env_file:
      - ./.env
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner-api
    command: node dist/index.js
    ports:
      - "4000:4000"
    networks:
      - enginy-network-prod
    env_file:
      - ./.env
    restart: always

networks:
  enginy-network-prod:
    driver: bridge