services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: enginy_backend_prod
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    networks:
      - enginy-network-prod
    command: bun start

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: enginy_frontend_prod
    ports:
      - "8080:80"
    networks:
      - enginy-network-prod

networks:
  enginy-network-prod:
    driver: bridge
