services:
  # Base de Datos (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: enginy_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: enginy_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - enginy-network

  # Backend API
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base # En dev usamos la base para tener hot-reload
    # Comando mÃ¡gico: Instala -> Genera Prisma -> Arranca Dev
    command: sh -c "npm install && npx prisma generate && npm run dev"
    working_dir: /app/apps/api
    volumes:
      - ./apps/api:/app/apps/api
      - ./packages:/app/packages
      - /app/node_modules
      - /app/apps/api/node_modules
    ports:
      - "4000:4000"
    env_file:
      - ./apps/api/.env # Lee SU propio archivo
    depends_on:
      - db
    networks:
      - enginy-network

  # Frontend Web
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    command: sh -c "npm install && npm run dev"
    working_dir: /app/apps/web
    volumes:
      - ./apps/web:/app/apps/web
      - ./packages:/app/packages
      - /app/node_modules
      - /app/apps/web/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./apps/web/.env # Lee SU propio archivo
    networks:
      - enginy-network

networks:
  enginy-network:
    driver: bridge

volumes:
  postgres_data: