services:
  web:
    image: ghcr.io/inspedralbes/tr2-reptes-tr2-g2-web:latest
    restart: always
    ports:
      - "8002:8002"
    env_file:
      - path: .env
        required: true
      - path: ./apps/web/.env
        required: false
    networks:
      - iter-network-prod
    volumes:
      - iter-uploads:/app/uploads

  api:
    image: ghcr.io/inspedralbes/tr2-reptes-tr2-g2-api:latest
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - path: .env
        required: true
      - path: ./apps/api/.env
        required: false
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - iter-network-prod
    volumes:
      - iter-uploads:/app/uploads

networks:
  iter-network-prod:
    driver: bridge

volumes:
  iter-uploads:
    driver: local
