services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "8002:80" # Permitir acceso directo por 8002 si el tunnel apunta ah√≠
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - api
    networks:
      - iter-network-prod

  web:
    image: ghcr.io/inspedralbes/tr2-reptes-tr2-g2-web:latest
    restart: always
    expose:
      - "8002"
    env_file:
      - path: .env
        required: true
      - path: ./apps/web/.env
        required: false
    networks:
      - iter-network-prod
    volumes:
      - iter-uploads:/app/uploads

  api:
    image: ghcr.io/inspedralbes/tr2-reptes-tr2-g2-api:latest
    restart: always
    expose:
      - "3000"
    env_file:
      - path: .env
        required: true
      - path: ./apps/api/.env
        required: false
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - iter-network-prod
    volumes:
      - iter-uploads:/app/uploads

networks:
  iter-network-prod:
    driver: bridge

volumes:
  iter-uploads:
    driver: local
