services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: runner-web
    restart: always
    ports:
      - "8002:8002"
    env_file:
      - path: .env
        required: true
      - path: ./apps/web/.env
        required: false
    networks:
      - iter-network-prod
    volumes:
      - iter-uploads:/app/uploads

  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: runner-api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - path: .env
        required: true
      - path: ./apps/api/.env
        required: false
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - iter-network-prod
    volumes:
      - iter-uploads:/app/uploads

networks:
  iter-network-prod:
    driver: bridge

volumes:
  iter-uploads:
    driver: local