services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder-web # Asegúrate que tu Dockerfile tenga este stage
    volumes:
      - .:/app
      - /app/node_modules # Truco para que no borre los node_modules del contenedor
    command: npm run dev --filter=web
    ports:
      - "3000:3000"
    networks:
      - enginy-network
    env_file:
      - ./.env

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder-api # Asegúrate que tu Dockerfile tenga este stage
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev --filter=api
    ports:
      - "4000:4000"
    networks:
      - enginy-network
    env_file:
      - ./.env
    # Ya no depende de mongodb

networks:
  enginy-network:
    driver: bridge