services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: enginy_backend_prod
    restart: always
    env_file:
      - .env.prod
    networks:
      - enginy-network-prod
    ports:
      - "3000:3000" 


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: enginy_frontend_prod
    restart: always
    ports:
      - "8002:80"
    networks:
      - enginy-network-prod
    depends_on:
      - backend

networks:
  enginy-network-prod:
    driver: bridge