services:
  db:
    image: postgres:15-alpine
    container_name: iter_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: iter_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - iter-network-prod

  adminer:
    image: adminer
    container_name: iter_adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - iter-network-prod

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8002:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - api
    networks:
      - iter-network-prod

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner-web
      args:
        - NEXT_PUBLIC_API_URL=https://iter.kore29.com/api
    image: ghcr.io/inspedralbes/tr2-reptes-tr2-g2-web:latest
    restart: always
    expose:
      - "3000"
    env_file:
      - path: .env
        required: true
      - path: ./apps/web/.env
        required: false
    networks:
      - iter-network-prod
    volumes:
      - iter-uploads:/app/uploads

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner-api
    image: ghcr.io/inspedralbes/tr2-reptes-tr2-g2-api:latest
    restart: always
    expose:
      - "3000"
    env_file:
      - path: .env
        required: true
      - path: ./apps/api/.env
        required: false
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
    networks:
      - iter-network-prod
    volumes:
      - iter-uploads:/app/uploads

networks:
  iter-network-prod:
    driver: bridge

volumes:
  iter-uploads:
    driver: local
  postgres_data:
