services:
  # En producción REAL, la DB suele estar fuera (AWS RDS, Atlas, etc).
  # Pero si la quieres en Docker también, descomenta estas líneas:
  # db:
  #   image: postgres:15-alpine
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_DB: iter_db
  #   volumes:
  #     - postgres_prod_data:/var/lib/postgresql/data
  #   networks:
  #     - iter-network-prod

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner-web
    restart: always
    ports:
      - "8002:8002"
    env_file:
      - ./apps/web/.env
    networks:
      - iter-network-prod

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner-api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./apps/api/.env
    networks:
      - iter-network-prod

networks:
  iter-network-prod:
    driver: bridge

# volumes:
#   postgres_prod_data: