services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: runner-web
    restart: always
    ports:
      - "8002:8002"
    env_file:
      - ./apps/web/.env
    networks:
      - iter-network-prod

  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: runner-api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./apps/api/.env
    # Afegeix extra_hosts per permetre la connexió a la base de dades local del host.
    # Al teu arxiu .env a apps/api, configura la DATABASE_URL així:
    # DATABASE_URL="postgresql://USER:PASSWORD@host.docker.internal:5432/DATABASE"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - iter-network-prod

networks:
  iter-network-prod:
    driver: bridge