services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: enginy_backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DB_HOST=mongodb
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    networks:
      - enginy-network
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: enginy_frontend
    ports:
      - "8081:8081" # Expo dev server runs on 8081
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - enginy-network
    stdin_open: true
    tty: true
    env_file:
      - .env

  mongodb:
    image: mongo:latest
    container_name: enginy_db
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    env_file:
      - .env
    volumes:
      - mongo_enginy_data:/data/db
    networks:
      - enginy-network

  mongo-express:
    image: mongo-express
    container_name: enginy_gui
    restart: always
    ports:
      - "27018:8081"
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/
    networks:
      - enginy-network
    depends_on:
      - mongodb

volumes:
  mongo_enginy_data:

networks:
  enginy-network:
    driver: bridge
