services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: runner-web
    restart: always
    env_file:
      - path: .env
        required: true
      - path: ./apps/web/.env
        required: false
    networks:
      - iter-network-prod

  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: runner-api
    restart: always
    env_file:
      - path: .env
        required: true
      - path: ./apps/api/.env
        required: false
    networks:
      - iter-network-prod

  nginx:
    image: nginx:alpine
    container_name: iter_nginx
    restart: always
    ports:
      - "8002:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - api
    networks:
      - iter-network-prod

networks:
  iter-network-prod:
    driver: bridge
