services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: enginy_backend_prod
    restart: always
    env_file:
      - .env.prod
    environment:
      - NODE_ENV=production
    networks:
      - enginy-network-prod
    ports:
      - "3000:3000"

  frontend:
    build:
      context: . 
      dockerfile: frontend/Dockerfile.prod 
    container_name: enginy_frontend_prod
    restart: always
    env_file:
      - .env.prod
    environment:
      - NODE_ENV=production
    ports:
      - "8002:80"
    networks:
      - enginy-network-prod
    depends_on:
      - backend

networks:
  enginy-network-prod:
    driver: bridge