services:
  mongodb:
    image: mongo:latest
    container_name: enginy_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "${MONGO_PORT}:27017"
    env_file:
      - .env.dev
    volumes:
      - mongo_enginy_data:/data/db
    networks:
      - enginy-network

  mongo-express:
    image: mongo-express
    container_name: enginy_gui
    restart: always
    ports:
      - "27018:8081"
    env_file:
    - .env.dev
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/
    networks:
      - enginy-network
    depends_on:
      - mongodb

volumes:
  mongo_enginy_data:

networks:
  enginy-network:
    driver: bridge